Allow retrieval of connection(s) and package data flow as JSON string
xplenty/xplenty.py pull request #34
Opened 2022-04-05 15:51 UTC by patricker

- Adds an optional parameter to `get_package` that allows you to retrieve the `data_flow_json` property.
 - Adds methods for retrieving connection names/details.

2022-04-07 05:54 UTC, danmun requested changes

2022-04-07 05:54 UTC, danmun commented on xplenty/xplenty_api.py
> +                'unique_id', 'username', 'type',
Is `username` included twice on purpose? If not, could you please remove one of them?

2022-04-07 05:54 UTC, danmun commented on xplenty/xplenty_api.py
> +    _strs = ['name', 'description', 'url','data_flow_json']
Could you please add a space after the last comma (for consistency)?

2022-04-07 15:17 UTC, patricker commented
@danmun Thanks for the feedback, let me know if there are any other changes I can make.

2022-04-11 05:37 UTC, danmun commented
@patricker Yes, one last thing, could you please bump the version from `3.0.0` to `3.1.0` in `setup.py`?

2022-04-15 14:42 UTC, patricker commented
@danmun Thanks for the feedback. I've been on a trip, but I've updated the code now.

2022-05-09 03:45 UTC, danmun approved these changes

2022-05-11 02:40 UTC, patricker commented
@danmun I don't have merge access. Can you merge this?

2024-06-20 15:58 UTC, closed without merging